# Source language and JDK version to use
language: java
jdk: oraclejdk8
dist: trusty

# Compile and package JAR and set build properties
install: ./gradlew setupCIWorkspace
script: ./gradlew build -PbuildNumber=$TRAVIS_BUILD_NUMBER -PciSystem=travis -Pcommit=${TRAVIS_COMMIT:0:7}

# Perform steps after compilation/test success
after_success:
  # Check if commit s not a pull request, if git repo is official, and if branch is 1.7. If checks pass, add libs and deploy artifacts to Maven repository.
  #- "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == Ordinastie/MalisisCore ]] && [[ $TRAVIS_BRANCH == 1.8.9]] && ./gradlew uploadArchives"
  - '[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == AlmuraDev/MalisisCore ]] && ./gradlew -PsonatypeUsername="${SONATYPE_USERNAME}" -PsonatypePassword="${SONATYPE_PASSWORD}" uploadArchives'

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
